/* =========================================
   KAISEKI SHUNEI — LANG.JS
   Système de traduction 15 langues
   ========================================= */

const translations = {
    FR: {
        // Menu latéral
        nav_reserver:     "RÉSERVER",
        nav_restaurant:   "LE RESTAURANT",
        nav_chefs:        "LES CHEFS",
        nav_experience:   "L'EXPÉRIENCE",
        nav_menu:         "LE MENU",
        nav_informations: "INFORMATIONS",
        nav_admin:        "ADMINISTRATION",
        // Header
        header_bienvenue: "BIENVENUE",
        btn_connexion:    "CONNEXION",
        btn_commander:    "COMMANDER",
        btn_deconnexion:  "DÉCONNEXION",
        // Hero
        hero_title:       "L'Art de la Perfection",
        hero_search:      "Rechercher une saveur...",
        // Connexion
        conn_titre:       "CONNEXION",
        conn_sous:        "Accédez à votre espace Kaiseki",
        conn_email:       "Email",
        conn_mdp:         "Mot de passe",
        conn_btn:         "SE CONNECTER",
        conn_switch:      "Pas encore de compte ?",
        conn_inscrire:    "S'inscrire",
        // Restaurant
        rest_heritage:    "NOTRE HÉRITAGE",
        rest_citation:    "\"Sous l'ombre des cerisiers de Kyoto...\"",
        // Chefs
        chef1_role:       "MAÎTRE DU FEU",
        chef2_role:       "ÂME CRÉATRICE",
        // Expérience
        exp_sous:         "NOTRE ODYSSÉE",
        exp_titre:        "L'Équilibre Absolu",
        exp_date1:        "2012",
        exp_titre1:       "La Rencontre",
        exp_texte1:       "Kenji et Aiko croisent leurs chemins dans les cuisines d'un grand Ryokan à Kyoto.",
        exp_date2:        "2018",
        exp_titre2:       "L'Ancrage Parisien",
        exp_texte2:       "Ouverture de Shunei au cœur de Montmartre.",
        exp_date3:        "2024",
        exp_titre3:       "La Consécration",
        exp_texte3:       "Le restaurant devient une référence mondiale du Kaiseki moderne.",
        exp_citation:     "\"Le sushi est un pont entre nos deux mondes.\"",
        // Menu
        menu_decouvrir:   "DÉCOUVRIR",
        menu_carte:       "LA CARTE",
        menu_entrer:      "ENTRER DANS L'EXPÉRIENCE",
        // Contact
        contact_nous:     "NOUS TROUVER",
        contact_titre:    "CONTACT",
        contact_adresse:  "ADRESSE",
        contact_horaires: "HORAIRES",
        contact_resa:     "RÉSERVATIONS",
        contact_val_h:    "Mardi — Samedi : 19:00 - 22:30",
        footer_copy:      "© 2026 KAISEKI SHUNEI — TOUS DROITS RÉSERVÉS",
    },
    EN: {
        nav_reserver:     "BOOK",
        nav_restaurant:   "THE RESTAURANT",
        nav_chefs:        "THE CHEFS",
        nav_experience:   "THE EXPERIENCE",
        nav_menu:         "THE MENU",
        nav_informations: "INFORMATION",
        nav_admin:        "ADMINISTRATION",
        header_bienvenue: "WELCOME",
        btn_connexion:    "LOGIN",
        btn_commander:    "ORDER",
        btn_deconnexion:  "LOGOUT",
        hero_title:       "The Art of Perfection",
        hero_search:      "Search for a flavor...",
        conn_titre:       "LOGIN",
        conn_sous:        "Access your Kaiseki account",
        conn_email:       "Email",
        conn_mdp:         "Password",
        conn_btn:         "SIGN IN",
        conn_switch:      "No account yet?",
        conn_inscrire:    "Sign up",
        rest_heritage:    "OUR HERITAGE",
        rest_citation:    "\"Beneath the cherry blossoms of Kyoto...\"",
        chef1_role:       "MASTER OF FIRE",
        chef2_role:       "CREATIVE SOUL",
        exp_sous:         "OUR JOURNEY",
        exp_titre:        "The Perfect Balance",
        exp_date1:        "2012",
        exp_titre1:       "The Meeting",
        exp_texte1:       "Kenji and Aiko cross paths in the kitchens of a grand Ryokan in Kyoto.",
        exp_date2:        "2018",
        exp_titre2:       "Paris Anchoring",
        exp_texte2:       "Opening of Shunei in the heart of Montmartre.",
        exp_date3:        "2024",
        exp_titre3:       "The Consecration",
        exp_texte3:       "The restaurant becomes a world reference of modern Kaiseki.",
        exp_citation:     "\"Sushi is a bridge between our two worlds.\"",
        menu_decouvrir:   "DISCOVER",
        menu_carte:       "THE MENU",
        menu_entrer:      "ENTER THE EXPERIENCE",
        contact_nous:     "FIND US",
        contact_titre:    "CONTACT",
        contact_adresse:  "ADDRESS",
        contact_horaires: "HOURS",
        contact_resa:     "RESERVATIONS",
        contact_val_h:    "Tuesday — Saturday: 7:00 PM - 10:30 PM",
        footer_copy:      "© 2026 KAISEKI SHUNEI — ALL RIGHTS RESERVED",
    },
    ES: {
        nav_reserver:     "RESERVAR",
        nav_restaurant:   "EL RESTAURANTE",
        nav_chefs:        "LOS CHEFS",
        nav_experience:   "LA EXPERIENCIA",
        nav_menu:         "EL MENÚ",
        nav_informations: "INFORMACIÓN",
        nav_admin:        "ADMINISTRACIÓN",
        header_bienvenue: "BIENVENIDO",
        btn_connexion:    "INICIAR SESIÓN",
        btn_commander:    "PEDIR",
        btn_deconnexion:  "CERRAR SESIÓN",
        hero_title:       "El Arte de la Perfección",
        hero_search:      "Buscar un sabor...",
        conn_titre:       "INICIAR SESIÓN",
        conn_sous:        "Accede a tu espacio Kaiseki",
        conn_email:       "Correo electrónico",
        conn_mdp:         "Contraseña",
        conn_btn:         "CONECTARSE",
        conn_switch:      "¿Aún no tienes cuenta?",
        conn_inscrire:    "Registrarse",
        rest_heritage:    "NUESTRO PATRIMONIO",
        rest_citation:    "\"Bajo la sombra de los cerezos de Kioto...\"",
        chef1_role:       "MAESTRO DEL FUEGO",
        chef2_role:       "ALMA CREATIVA",
        exp_sous:         "NUESTRO VIAJE",
        exp_titre:        "El Equilibrio Absoluto",
        exp_date1:        "2012",
        exp_titre1:       "El Encuentro",
        exp_texte1:       "Kenji y Aiko se cruzan en las cocinas de un gran Ryokan en Kioto.",
        exp_date2:        "2018",
        exp_titre2:       "El Anclaje Parisino",
        exp_texte2:       "Apertura de Shunei en el corazón de Montmartre.",
        exp_date3:        "2024",
        exp_titre3:       "La Consagración",
        exp_texte3:       "El restaurante se convierte en referencia mundial del Kaiseki moderno.",
        exp_citation:     "\"El sushi es un puente entre nuestros dos mundos.\"",
        menu_decouvrir:   "DESCUBRIR",
        menu_carte:       "LA CARTA",
        menu_entrer:      "ENTRAR EN LA EXPERIENCIA",
        contact_nous:     "ENCUÉNTRANOS",
        contact_titre:    "CONTACTO",
        contact_adresse:  "DIRECCIÓN",
        contact_horaires: "HORARIOS",
        contact_resa:     "RESERVAS",
        contact_val_h:    "Martes — Sábado: 19:00 - 22:30",
        footer_copy:      "© 2026 KAISEKI SHUNEI — TODOS LOS DERECHOS RESERVADOS",
    },
    DE: {
        nav_reserver:     "RESERVIEREN",
        nav_restaurant:   "DAS RESTAURANT",
        nav_chefs:        "DIE KÖCHE",
        nav_experience:   "DIE ERFAHRUNG",
        nav_menu:         "DIE SPEISEKARTE",
        nav_informations: "INFORMATION",
        nav_admin:        "VERWALTUNG",
        header_bienvenue: "WILLKOMMEN",
        btn_connexion:    "ANMELDEN",
        btn_commander:    "BESTELLEN",
        btn_deconnexion:  "ABMELDEN",
        hero_title:       "Die Kunst der Perfektion",
        hero_search:      "Einen Geschmack suchen...",
        conn_titre:       "ANMELDEN",
        conn_sous:        "Zugang zu Ihrem Kaiseki-Bereich",
        conn_email:       "E-Mail",
        conn_mdp:         "Passwort",
        conn_btn:         "EINLOGGEN",
        conn_switch:      "Noch kein Konto?",
        conn_inscrire:    "Registrieren",
        rest_heritage:    "UNSER ERBE",
        rest_citation:    "\"Im Schatten der Kirschblüten von Kyoto...\"",
        chef1_role:       "MEISTER DES FEUERS",
        chef2_role:       "KREATIVE SEELE",
        exp_sous:         "UNSERE REISE",
        exp_titre:        "Das Absolute Gleichgewicht",
        exp_date1:        "2012",
        exp_titre1:       "Die Begegnung",
        exp_texte1:       "Kenji und Aiko begegnen sich in den Küchen eines großen Ryokans in Kyoto.",
        exp_date2:        "2018",
        exp_titre2:       "Pariser Verankerung",
        exp_texte2:       "Eröffnung von Shunei im Herzen von Montmartre.",
        exp_date3:        "2024",
        exp_titre3:       "Die Weihe",
        exp_texte3:       "Das Restaurant wird zur weltweiten Referenz des modernen Kaiseki.",
        exp_citation:     "\"Sushi ist eine Brücke zwischen unseren beiden Welten.\"",
        menu_decouvrir:   "ENTDECKEN",
        menu_carte:       "DIE SPEISEKARTE",
        menu_entrer:      "IN DIE ERFAHRUNG EINTRETEN",
        contact_nous:     "UNS FINDEN",
        contact_titre:    "KONTAKT",
        contact_adresse:  "ADRESSE",
        contact_horaires: "ÖFFNUNGSZEITEN",
        contact_resa:     "RESERVIERUNGEN",
        contact_val_h:    "Dienstag — Samstag: 19:00 - 22:30",
        footer_copy:      "© 2026 KAISEKI SHUNEI — ALLE RECHTE VORBEHALTEN",
    },
    JA: {
        nav_reserver:     "予約",
        nav_restaurant:   "レストラン",
        nav_chefs:        "シェフたち",
        nav_experience:   "体験",
        nav_menu:         "メニュー",
        nav_informations: "情報",
        nav_admin:        "管理",
        header_bienvenue: "ようこそ",
        btn_connexion:    "ログイン",
        btn_commander:    "注文する",
        btn_deconnexion:  "ログアウト",
        hero_title:       "完璧の芸術",
        hero_search:      "風味を探す...",
        conn_titre:       "ログイン",
        conn_sous:        "Kaisekiアカウントにアクセス",
        conn_email:       "メール",
        conn_mdp:         "パスワード",
        conn_btn:         "サインイン",
        conn_switch:      "アカウントをお持ちでない方は？",
        conn_inscrire:    "登録する",
        rest_heritage:    "私たちの遺産",
        rest_citation:    "「京都の桜の陰で...」",
        chef1_role:       "火の達人",
        chef2_role:       "創造の魂",
        exp_sous:         "私たちの旅",
        exp_titre:        "完璧なバランス",
        exp_date1:        "2012",
        exp_titre1:       "出会い",
        exp_texte1:       "ケンジとアイコは京都の旅館の厨房で出会いました。",
        exp_date2:        "2018",
        exp_titre2:       "パリへの定着",
        exp_texte2:       "モンマルトルの中心部にシュネイをオープン。",
        exp_date3:        "2024",
        exp_titre3:       "栄光",
        exp_texte3:       "レストランはモダン懐石の世界的な参照となった。",
        exp_citation:     "「寿司は私たちの二つの世界の橋です。」",
        menu_decouvrir:   "発見する",
        menu_carte:       "メニュー",
        menu_entrer:      "体験に入る",
        contact_nous:     "アクセス",
        contact_titre:    "お問い合わせ",
        contact_adresse:  "住所",
        contact_horaires: "営業時間",
        contact_resa:     "予約",
        contact_val_h:    "火曜〜土曜: 19:00 - 22:30",
        footer_copy:      "© 2026 KAISEKI SHUNEI — 全著作権所有",
    },
    RU: {
        nav_reserver:     "ЗАБРОНИРОВАТЬ",
        nav_restaurant:   "РЕСТОРАН",
        nav_chefs:        "ШЕФЫ",
        nav_experience:   "ОПЫТ",
        nav_menu:         "МЕНЮ",
        nav_informations: "ИНФОРМАЦИЯ",
        nav_admin:        "АДМИНИСТРАЦИЯ",
        header_bienvenue: "ДОБРО ПОЖАЛОВАТЬ",
        btn_connexion:    "ВОЙТИ",
        btn_commander:    "ЗАКАЗАТЬ",
        btn_deconnexion:  "ВЫЙТИ",
        hero_title:       "Искусство Совершенства",
        hero_search:      "Искать вкус...",
        conn_titre:       "ВХОД",
        conn_sous:        "Доступ к вашему аккаунту Kaiseki",
        conn_email:       "Электронная почта",
        conn_mdp:         "Пароль",
        conn_btn:         "ВОЙТИ",
        conn_switch:      "Нет аккаунта?",
        conn_inscrire:    "Зарегистрироваться",
        rest_heritage:    "НАШЕ НАСЛЕДИЕ",
        rest_citation:    "\"В тени сакуры Киото...\"",
        chef1_role:       "МАСТЕР ОГНЯ",
        chef2_role:       "ТВОРЧЕСКАЯ ДУША",
        exp_sous:         "НАШ ПУТЬ",
        exp_titre:        "Абсолютное Равновесие",
        exp_date1:        "2012",
        exp_titre1:       "Встреча",
        exp_texte1:       "Кэндзи и Айко встретились на кухне рёкана в Киото.",
        exp_date2:        "2018",
        exp_titre2:       "Парижское Основание",
        exp_texte2:       "Открытие Shunei в сердце Монмартра.",
        exp_date3:        "2024",
        exp_titre3:       "Признание",
        exp_texte3:       "Ресторан становится мировым эталоном современного кайсэки.",
        exp_citation:     "\"Суши — это мост между нашими двумя мирами.\"",
        menu_decouvrir:   "ОТКРЫТЬ",
        menu_carte:       "МЕНЮ",
        menu_entrer:      "ВОЙТИ В ОПЫТ",
        contact_nous:     "КАК НАС НАЙТИ",
        contact_titre:    "КОНТАКТЫ",
        contact_adresse:  "АДРЕС",
        contact_horaires: "ЧАСЫ РАБОТЫ",
        contact_resa:     "БРОНИРОВАНИЕ",
        contact_val_h:    "Вторник — Суббота: 19:00 - 22:30",
        footer_copy:      "© 2026 KAISEKI SHUNEI — ВСЕ ПРАВА ЗАЩИЩЕНЫ",
    },
    AR: {
        nav_reserver:     "حجز",
        nav_restaurant:   "المطعم",
        nav_chefs:        "الطهاة",
        nav_experience:   "التجربة",
        nav_menu:         "القائمة",
        nav_informations: "معلومات",
        nav_admin:        "الإدارة",
        header_bienvenue: "مرحباً",
        btn_connexion:    "تسجيل الدخول",
        btn_commander:    "طلب",
        btn_deconnexion:  "تسجيل الخروج",
        hero_title:       "فن الكمال",
        hero_search:      "ابحث عن نكهة...",
        conn_titre:       "تسجيل الدخول",
        conn_sous:        "الوصول إلى حسابك في كايسيكي",
        conn_email:       "البريد الإلكتروني",
        conn_mdp:         "كلمة المرور",
        conn_btn:         "دخول",
        conn_switch:      "ليس لديك حساب؟",
        conn_inscrire:    "التسجيل",
        rest_heritage:    "تراثنا",
        rest_citation:    "\"تحت ظلال أزهار الكرز في كيوتو...\"",
        chef1_role:       "سيد النار",
        chef2_role:       "الروح الإبداعية",
        exp_sous:         "رحلتنا",
        exp_titre:        "التوازن المطلق",
        exp_date1:        "2012",
        exp_titre1:       "اللقاء",
        exp_texte1:       "التقى كينجي وأيكو في مطابخ فندق ريوكان الكبير في كيوتو.",
        exp_date2:        "2018",
        exp_titre2:       "الاستقرار في باريس",
        exp_texte2:       "افتتاح شونيي في قلب مونمارتر.",
        exp_date3:        "2024",
        exp_titre3:       "التتويج",
        exp_texte3:       "أصبح المطعم مرجعاً عالمياً للكايسيكي الحديث.",
        exp_citation:     "\"السوشي جسر بين عالمينا.\"",
        menu_decouvrir:   "اكتشف",
        menu_carte:       "القائمة",
        menu_entrer:      "ادخل التجربة",
        contact_nous:     "ابحث عنا",
        contact_titre:    "اتصل بنا",
        contact_adresse:  "العنوان",
        contact_horaires: "ساعات العمل",
        contact_resa:     "الحجوزات",
        contact_val_h:    "الثلاثاء — السبت: 19:00 - 22:30",
        footer_copy:      "© 2026 KAISEKI SHUNEI — جميع الحقوق محفوظة",
    },
    KO: {
        nav_reserver:     "예약",
        nav_restaurant:   "레스토랑",
        nav_chefs:        "셰프들",
        nav_experience:   "경험",
        nav_menu:         "메뉴",
        nav_informations: "정보",
        nav_admin:        "관리",
        header_bienvenue: "환영합니다",
        btn_connexion:    "로그인",
        btn_commander:    "주문하기",
        btn_deconnexion:  "로그아웃",
        hero_title:       "완벽의 예술",
        hero_search:      "맛을 검색하세요...",
        conn_titre:       "로그인",
        conn_sous:        "Kaiseki 계정에 접속",
        conn_email:       "이메일",
        conn_mdp:         "비밀번호",
        conn_btn:         "로그인",
        conn_switch:      "계정이 없으신가요?",
        conn_inscrire:    "회원가입",
        rest_heritage:    "우리의 유산",
        rest_citation:    "\"교토 벚꽃 나무 그늘 아래...\"",
        chef1_role:       "불의 달인",
        chef2_role:       "창조적 영혼",
        exp_sous:         "우리의 여정",
        exp_titre:        "완벽한 균형",
        exp_date1:        "2012",
        exp_titre1:       "만남",
        exp_texte1:       "켄지와 아이코는 교토의 료칸 주방에서 만났습니다.",
        exp_date2:        "2018",
        exp_titre2:       "파리 정착",
        exp_texte2:       "몽마르트르 중심에 슈네이 개업.",
        exp_date3:        "2024",
        exp_titre3:       "영광",
        exp_texte3:       "레스토랑은 현대 가이세키의 세계적 기준이 됩니다.",
        exp_citation:     "\"스시는 우리 두 세계의 다리입니다.\"",
        menu_decouvrir:   "발견하기",
        menu_carte:       "메뉴",
        menu_entrer:      "경험 속으로",
        contact_nous:     "찾아오시는 길",
        contact_titre:    "연락처",
        contact_adresse:  "주소",
        contact_horaires: "영업시간",
        contact_resa:     "예약",
        contact_val_h:    "화요일 — 토요일: 19:00 - 22:30",
        footer_copy:      "© 2026 KAISEKI SHUNEI — 모든 권리 보유",
    },
    ZH: {
        nav_reserver:     "预订",
        nav_restaurant:   "餐厅",
        nav_chefs:        "厨师",
        nav_experience:   "体验",
        nav_menu:         "菜单",
        nav_informations: "信息",
        nav_admin:        "管理",
        header_bienvenue: "欢迎",
        btn_connexion:    "登录",
        btn_commander:    "点餐",
        btn_deconnexion:  "退出",
        hero_title:       "完美的艺术",
        hero_search:      "搜索口味...",
        conn_titre:       "登录",
        conn_sous:        "访问您的Kaiseki账户",
        conn_email:       "电子邮件",
        conn_mdp:         "密码",
        conn_btn:         "登录",
        conn_switch:      "还没有账户？",
        conn_inscrire:    "注册",
        rest_heritage:    "我们的遗产",
        rest_citation:    "\"在京都樱花树的阴影下...\"",
        chef1_role:       "火焰大师",
        chef2_role:       "创意灵魂",
        exp_sous:         "我们的旅程",
        exp_titre:        "绝对平衡",
        exp_date1:        "2012",
        exp_titre1:       "相遇",
        exp_texte1:       "健二和爱子在京都一家旅馆的厨房相遇。",
        exp_date2:        "2018",
        exp_titre2:       "巴黎定居",
        exp_texte2:       "在蒙马特中心开设春荣。",
        exp_date3:        "2024",
        exp_titre3:       "成就",
        exp_texte3:       "餐厅成为现代怀石料理的世界标杆。",
        exp_citation:     "\"寿司是我们两个世界之间的桥梁。\"",
        menu_decouvrir:   "发现",
        menu_carte:       "菜单",
        menu_entrer:      "进入体验",
        contact_nous:     "找到我们",
        contact_titre:    "联系",
        contact_adresse:  "地址",
        contact_horaires: "营业时间",
        contact_resa:     "预订",
        contact_val_h:    "周二 — 周六: 19:00 - 22:30",
        footer_copy:      "© 2026 KAISEKI SHUNEI — 版权所有",
    },
    IT: {
        nav_reserver:     "PRENOTARE",
        nav_restaurant:   "IL RISTORANTE",
        nav_chefs:        "I CHEF",
        nav_experience:   "L'ESPERIENZA",
        nav_menu:         "IL MENU",
        nav_informations: "INFORMAZIONI",
        nav_admin:        "AMMINISTRAZIONE",
        header_bienvenue: "BENVENUTO",
        btn_connexion:    "ACCEDI",
        btn_commander:    "ORDINA",
        btn_deconnexion:  "DISCONNETTI",
        hero_title:       "L'Arte della Perfezione",
        hero_search:      "Cerca un sapore...",
        conn_titre:       "ACCEDI",
        conn_sous:        "Accedi al tuo spazio Kaiseki",
        conn_email:       "Email",
        conn_mdp:         "Password",
        conn_btn:         "ACCEDI",
        conn_switch:      "Non hai ancora un account?",
        conn_inscrire:    "Registrati",
        rest_heritage:    "IL NOSTRO PATRIMONIO",
        rest_citation:    "\"All'ombra dei ciliegi di Kyoto...\"",
        chef1_role:       "MAESTRO DEL FUOCO",
        chef2_role:       "ANIMA CREATIVA",
        exp_sous:         "IL NOSTRO VIAGGIO",
        exp_titre:        "L'Equilibrio Assoluto",
        exp_date1:        "2012",
        exp_titre1:       "L'Incontro",
        exp_texte1:       "Kenji e Aiko si incontrano nelle cucine di un grande Ryokan a Kyoto.",
        exp_date2:        "2018",
        exp_titre2:       "L'Ancoraggio Parigino",
        exp_texte2:       "Apertura di Shunei nel cuore di Montmartre.",
        exp_date3:        "2024",
        exp_titre3:       "La Consacrazione",
        exp_texte3:       "Il ristorante diventa un riferimento mondiale del Kaiseki moderno.",
        exp_citation:     "\"Il sushi è un ponte tra i nostri due mondi.\"",
        menu_decouvrir:   "SCOPRIRE",
        menu_carte:       "IL MENU",
        menu_entrer:      "ENTRARE NELL'ESPERIENZA",
        contact_nous:     "TROVACI",
        contact_titre:    "CONTATTO",
        contact_adresse:  "INDIRIZZO",
        contact_horaires: "ORARI",
        contact_resa:     "PRENOTAZIONI",
        contact_val_h:    "Martedì — Sabato: 19:00 - 22:30",
        footer_copy:      "© 2026 KAISEKI SHUNEI — TUTTI I DIRITTI RISERVATI",
    },
    PT: {
        nav_reserver:     "RESERVAR",
        nav_restaurant:   "O RESTAURANTE",
        nav_chefs:        "OS CHEFS",
        nav_experience:   "A EXPERIÊNCIA",
        nav_menu:         "O MENU",
        nav_informations: "INFORMAÇÃO",
        nav_admin:        "ADMINISTRAÇÃO",
        header_bienvenue: "BEM-VINDO",
        btn_connexion:    "ENTRAR",
        btn_commander:    "PEDIR",
        btn_deconnexion:  "SAIR",
        hero_title:       "A Arte da Perfeição",
        hero_search:      "Procurar um sabor...",
        conn_titre:       "ENTRAR",
        conn_sous:        "Aceda ao seu espaço Kaiseki",
        conn_email:       "Email",
        conn_mdp:         "Senha",
        conn_btn:         "ENTRAR",
        conn_switch:      "Ainda não tem conta?",
        conn_inscrire:    "Registar",
        rest_heritage:    "NOSSA HERANÇA",
        rest_citation:    "\"À sombra das cerejeiras de Kyoto...\"",
        chef1_role:       "MESTRE DO FOGO",
        chef2_role:       "ALMA CRIATIVA",
        exp_sous:         "NOSSA JORNADA",
        exp_titre:        "O Equilíbrio Absoluto",
        exp_date1:        "2012",
        exp_titre1:       "O Encontro",
        exp_texte1:       "Kenji e Aiko cruzam-se nas cozinhas de um grande Ryokan em Kyoto.",
        exp_date2:        "2018",
        exp_titre2:       "A Ancoragem Parisiense",
        exp_texte2:       "Abertura do Shunei no coração de Montmartre.",
        exp_date3:        "2024",
        exp_titre3:       "A Consagração",
        exp_texte3:       "O restaurante torna-se referência mundial do Kaiseki moderno.",
        exp_citation:     "\"O sushi é uma ponte entre os nossos dois mundos.\"",
        menu_decouvrir:   "DESCOBRIR",
        menu_carte:       "O MENU",
        menu_entrer:      "ENTRAR NA EXPERIÊNCIA",
        contact_nous:     "ENCONTRE-NOS",
        contact_titre:    "CONTACTO",
        contact_adresse:  "ENDEREÇO",
        contact_horaires: "HORÁRIOS",
        contact_resa:     "RESERVAS",
        contact_val_h:    "Terça — Sábado: 19:00 - 22:30",
        footer_copy:      "© 2026 KAISEKI SHUNEI — TODOS OS DIREITOS RESERVADOS",
    },
    NL: {
        nav_reserver:     "RESERVEREN",
        nav_restaurant:   "HET RESTAURANT",
        nav_chefs:        "DE CHEFS",
        nav_experience:   "DE ERVARING",
        nav_menu:         "HET MENU",
        nav_informations: "INFORMATIE",
        nav_admin:        "BEHEER",
        header_bienvenue: "WELKOM",
        btn_connexion:    "INLOGGEN",
        btn_commander:    "BESTELLEN",
        btn_deconnexion:  "UITLOGGEN",
        hero_title:       "De Kunst van Perfectie",
        hero_search:      "Zoek een smaak...",
        conn_titre:       "INLOGGEN",
        conn_sous:        "Toegang tot uw Kaiseki-account",
        conn_email:       "E-mail",
        conn_mdp:         "Wachtwoord",
        conn_btn:         "INLOGGEN",
        conn_switch:      "Nog geen account?",
        conn_inscrire:    "Registreren",
        rest_heritage:    "ONS ERFGOED",
        rest_citation:    "\"Onder de schaduw van de kersenbloesems van Kyoto...\"",
        chef1_role:       "MEESTER VAN HET VUUR",
        chef2_role:       "CREATIEVE ZIEL",
        exp_sous:         "ONZE REIS",
        exp_titre:        "Het Absolute Evenwicht",
        exp_date1:        "2012",
        exp_titre1:       "De Ontmoeting",
        exp_texte1:       "Kenji en Aiko ontmoeten elkaar in de keukens van een groot Ryokan in Kyoto.",
        exp_date2:        "2018",
        exp_titre2:       "Parijse Verankering",
        exp_texte2:       "Opening van Shunei in het hart van Montmartre.",
        exp_date3:        "2024",
        exp_titre3:       "De Wijding",
        exp_texte3:       "Het restaurant wordt een wereldwijde referentie voor moderne Kaiseki.",
        exp_citation:     "\"Sushi is een brug tussen onze twee werelden.\"",
        menu_decouvrir:   "ONTDEKKEN",
        menu_carte:       "HET MENU",
        menu_entrer:      "DE ERVARING BETREDEN",
        contact_nous:     "VIND ONS",
        contact_titre:    "CONTACT",
        contact_adresse:  "ADRES",
        contact_horaires: "OPENINGSTIJDEN",
        contact_resa:     "RESERVERINGEN",
        contact_val_h:    "Dinsdag — Zaterdag: 19:00 - 22:30",
        footer_copy:      "© 2026 KAISEKI SHUNEI — ALLE RECHTEN VOORBEHOUDEN",
    },
    HI: {
        nav_reserver:     "बुक करें",
        nav_restaurant:   "रेस्तरां",
        nav_chefs:        "शेफ",
        nav_experience:   "अनुभव",
        nav_menu:         "मेनू",
        nav_informations: "जानकारी",
        nav_admin:        "प्रशासन",
        header_bienvenue: "स्वागत है",
        btn_connexion:    "लॉगिन",
        btn_commander:    "ऑर्डर करें",
        btn_deconnexion:  "लॉगआउट",
        hero_title:       "परिपूर्णता की कला",
        hero_search:      "स्वाद खोजें...",
        conn_titre:       "लॉगिन",
        conn_sous:        "अपने Kaiseki खाते तक पहुंचें",
        conn_email:       "ईमेल",
        conn_mdp:         "पासवर्ड",
        conn_btn:         "साइन इन",
        conn_switch:      "अभी तक खाता नहीं है?",
        conn_inscrire:    "पंजीकरण करें",
        rest_heritage:    "हमारी विरासत",
        rest_citation:    "\"क्योटो के चेरी ब्लॉसम की छाया में...\"",
        chef1_role:       "आग के उस्ताद",
        chef2_role:       "रचनात्मक आत्मा",
        exp_sous:         "हमारी यात्रा",
        exp_titre:        "परम संतुलन",
        exp_date1:        "2012",
        exp_titre1:       "मुलाकात",
        exp_texte1:       "केंजी और आइको क्योटो के एक रयोकान की रसोई में मिले।",
        exp_date2:        "2018",
        exp_titre2:       "पेरिस में स्थापना",
        exp_texte2:       "मॉन्टमार्ट्रे के केंद्र में शुनेई का उद्घाटन।",
        exp_date3:        "2024",
        exp_titre3:       "सफलता",
        exp_texte3:       "रेस्तरां आधुनिक कैसेकी का विश्व संदर्भ बन गया।",
        exp_citation:     "\"सुशी हमारी दोनों दुनियाओं के बीच का पुल है।\"",
        menu_decouvrir:   "खोजें",
        menu_carte:       "मेनू",
        menu_entrer:      "अनुभव में प्रवेश करें",
        contact_nous:     "हमें खोजें",
        contact_titre:    "संपर्क",
        contact_adresse:  "पता",
        contact_horaires: "समय",
        contact_resa:     "आरक्षण",
        contact_val_h:    "मंगलवार — शनिवार: 19:00 - 22:30",
        footer_copy:      "© 2026 KAISEKI SHUNEI — सर्वाधिकार सुरक्षित",
    },
    TR: {
        nav_reserver:     "REZERVASYON",
        nav_restaurant:   "RESTORAN",
        nav_chefs:        "ŞEFLER",
        nav_experience:   "DENEYİM",
        nav_menu:         "MENÜ",
        nav_informations: "BİLGİ",
        nav_admin:        "YÖNETİM",
        header_bienvenue: "HOŞ GELDİNİZ",
        btn_connexion:    "GİRİŞ",
        btn_commander:    "SİPARİŞ",
        btn_deconnexion:  "ÇIKIŞ",
        hero_title:       "Mükemmelliğin Sanatı",
        hero_search:      "Bir lezzet arayın...",
        conn_titre:       "GİRİŞ YAP",
        conn_sous:        "Kaiseki hesabınıza erişin",
        conn_email:       "E-posta",
        conn_mdp:         "Şifre",
        conn_btn:         "GİRİŞ",
        conn_switch:      "Hesabınız yok mu?",
        conn_inscrire:    "Kayıt ol",
        rest_heritage:    "MİRASIMIZ",
        rest_citation:    "\"Kyoto'nun kiraz çiçeklerinin gölgesinde...\"",
        chef1_role:       "ATEŞ USTASI",
        chef2_role:       "YARATICI RUH",
        exp_sous:         "YOLCULUĞUMUZ",
        exp_titre:        "Mutlak Denge",
        exp_date1:        "2012",
        exp_titre1:       "Buluşma",
        exp_texte1:       "Kenji ve Aiko, Kyoto'daki büyük bir Ryokan'ın mutfaklarında tanıştı.",
        exp_date2:        "2018",
        exp_titre2:       "Paris'e Yerleşme",
        exp_texte2:       "Montmartre'ın kalbinde Shunei'nin açılışı.",
        exp_date3:        "2024",
        exp_titre3:       "Taçlanma",
        exp_texte3:       "Restoran, modern Kaiseki'nin dünya referansı haline geldi.",
        exp_citation:     "\"Suşi, iki dünyamız arasındaki köprüdür.\"",
        menu_decouvrir:   "KEŞFET",
        menu_carte:       "MENÜ",
        menu_entrer:      "DENEYİME GİR",
        contact_nous:     "BİZİ BULUN",
        contact_titre:    "İLETİŞİM",
        contact_adresse:  "ADRES",
        contact_horaires: "ÇALIŞMA SAATLERİ",
        contact_resa:     "REZERVASYONLAR",
        contact_val_h:    "Salı — Cumartesi: 19:00 - 22:30",
        footer_copy:      "© 2026 KAISEKI SHUNEI — TÜM HAKLAR SAKLIDIR",
    },
    PL: {
        nav_reserver:     "REZERWACJA",
        nav_restaurant:   "RESTAURACJA",
        nav_chefs:        "SZEFOWIE",
        nav_experience:   "DOŚWIADCZENIE",
        nav_menu:         "MENU",
        nav_informations: "INFORMACJE",
        nav_admin:        "ADMINISTRACJA",
        header_bienvenue: "WITAMY",
        btn_connexion:    "ZALOGUJ",
        btn_commander:    "ZAMÓW",
        btn_deconnexion:  "WYLOGUJ",
        hero_title:       "Sztuka Doskonałości",
        hero_search:      "Szukaj smaku...",
        conn_titre:       "ZALOGUJ SIĘ",
        conn_sous:        "Dostęp do konta Kaiseki",
        conn_email:       "Email",
        conn_mdp:         "Hasło",
        conn_btn:         "ZALOGUJ",
        conn_switch:      "Nie masz konta?",
        conn_inscrire:    "Zarejestruj się",
        rest_heritage:    "NASZE DZIEDZICTWO",
        rest_citation:    "\"W cieniu kwiatów wiśni Kioto...\"",
        chef1_role:       "MISTRZ OGNIA",
        chef2_role:       "TWÓRCZA DUSZA",
        exp_sous:         "NASZA PODRÓŻ",
        exp_titre:        "Absolutna Równowaga",
        exp_date1:        "2012",
        exp_titre1:       "Spotkanie",
        exp_texte1:       "Kenji i Aiko spotykają się w kuchniach wielkiego Ryokanu w Kioto.",
        exp_date2:        "2018",
        exp_titre2:       "Paryskie Zakorzenienie",
        exp_texte2:       "Otwarcie Shunei w sercu Montmartre'u.",
        exp_date3:        "2024",
        exp_titre3:       "Konsekracja",
        exp_texte3:       "Restauracja staje się światowym odniesieniem nowoczesnego Kaiseki.",
        exp_citation:     "\"Sushi to most między naszymi dwoma światami.\"",
        menu_decouvrir:   "ODKRYJ",
        menu_carte:       "MENU",
        menu_entrer:      "WEJDŹ W DOŚWIADCZENIE",
        contact_nous:     "ZNAJDŹ NAS",
        contact_titre:    "KONTAKT",
        contact_adresse:  "ADRES",
        contact_horaires: "GODZINY",
        contact_resa:     "REZERWACJE",
        contact_val_h:    "Wtorek — Sobota: 19:00 - 22:30",
        footer_copy:      "© 2026 KAISEKI SHUNEI — WSZELKIE PRAWA ZASTRZEŻONE",
    }
};

// ── FONCTION PRINCIPALE DE TRADUCTION ──
function applyLang(code) {
    const t = translations[code];
    if (!t) return;

    // Sauvegarder la langue
    localStorage.setItem('kaiseki_lang', code);
    document.getElementById('lang-current').textContent = code;

    // Direction RTL pour l'arabe
    document.documentElement.dir = (code === 'AR') ? 'rtl' : 'ltr';

    // Appliquer toutes les traductions
    const apply = (selector, key) => {
        const el = document.querySelector(selector);
        if (el && t[key]) el.textContent = t[key];
    };

    const applyPlaceholder = (selector, key) => {
        const el = document.querySelector(selector);
        if (el && t[key]) el.placeholder = t[key];
    };

    // Navigation
    const links = document.querySelectorAll('.menu-links a');
    const keys = ['nav_reserver','nav_restaurant','nav_chefs','nav_experience','nav_menu','nav_informations'];
    links.forEach((link, i) => { if (t[keys[i]]) link.textContent = t[keys[i]]; });

    // Boutons header
    apply('.btn-reservation',  'btn_commander');
    apply('.btn-deconnexion',  'btn_deconnexion');

    // Hero
    apply('.hero-content h2',  'hero_title');
    applyPlaceholder('.input-search', 'hero_search');

    // Panel connexion
    apply('.auth-box h3',      'conn_titre');
    apply('.auth-subtitle',    'conn_sous');
    applyPlaceholder('input[name="email"]',    'conn_email');
    applyPlaceholder('input[name="password"]', 'conn_mdp');
    apply('.btn-submit',       'conn_btn');
    apply('.switch-auth',      'conn_switch');

    // Restaurant
    apply('.section-subtitle', 'rest_heritage');

    // Chefs
    const chefRoles = document.querySelectorAll('.chef-role');
    if (chefRoles[0] && t['chef1_role']) chefRoles[0].textContent = t['chef1_role'];
    if (chefRoles[1] && t['chef2_role']) chefRoles[1].textContent = t['chef2_role'];

    // Expérience
    apply('.section-title-gold', 'exp_titre');
    apply('.exp-quote-large',    'exp_citation');

    const items = document.querySelectorAll('.timeline-content');
    if (items[0]) {
        items[0].querySelector('h3').textContent = t['exp_titre1'] || '';
        items[0].querySelector('p').textContent  = t['exp_texte1'] || '';
    }
    if (items[1]) {
        items[1].querySelector('h3').textContent = t['exp_titre2'] || '';
        items[1].querySelector('p').textContent  = t['exp_texte2'] || '';
    }
    if (items[2]) {
        items[2].querySelector('h3').textContent = t['exp_titre3'] || '';
        items[2].querySelector('p').textContent  = t['exp_texte3'] || '';
    }

    // Menu section
    apply('.menu-compact-box .section-subtitle', 'menu_decouvrir');
    apply('.menu-title-small',  'menu_carte');
    apply('.click-info',        'menu_entrer');

    // Contact
    apply('.info-block .section-subtitle', 'contact_nous');
    apply('.info-block h2',     'contact_titre');
    apply('.site-footer p',     'footer_copy');

    const labels = document.querySelectorAll('.detail-item .label');
    const valKeys = ['contact_adresse','contact_horaires','contact_resa'];
    labels.forEach((label, i) => { if (t[valKeys[i]]) label.textContent = t[valKeys[i]]; });

    const vals = document.querySelectorAll('.detail-item p:not(.label)');
    if (vals[1] && t['contact_val_h']) vals[1].textContent = t['contact_val_h'];
}

// ── INIT : charger la langue sauvegardée ──
document.addEventListener('DOMContentLoaded', () => {
    const saved = localStorage.getItem('kaiseki_lang') || 'FR';
    if (saved !== 'FR') applyLang(saved);
    document.getElementById('lang-current').textContent = saved;
});